export const TECH_STACK_SUGGESTIONS = [
  "React",
  "TypeScript",
  "Vue.js",
  "Angular",
  "Node.js",
  "Next.js",
  "Tailwind CSS",
  "GraphQL",
  "Docker",
  "PostgreSQL",
  "Vite",
  "ESLint",
  "Prettier",
  "Jest",
  "Vitest",
  "Playwright",
  "Cypress",
  "Redux",
  "Zustand",
  "TanStack Query",
];

export const LEARNING_SUGGESTIONS = [
  "Rust",
  "WebAssembly",
  "AI/ML",
  "Svelte",
  "Kubernetes",
  "Deno",
  "Micro-frontends (Module Federation)",
  "Serverless (AWS Lambda, Vercel Functions)",
  "Edge Computing",
  "Progressive Web Apps (PWA)",
  "Web Performance Optimization",
  "Real-time apps (WebSockets, SSE)",
  "Design Systems",
  "Accessibility (a11y)",
  "Testing strategies",
];
